config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: 'pages#home', as: 'home'
  get 'about', to: 'pages#about', as: 'about'
  get 'services', to: 'pages#services', as: 'services'
  get 'portfolio', to: 'pages#portfolio', as: 'portfolio'
  get 'contact', to: 'pages#contact', as: 'contact'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  helper_method :image_mapping
  def home; end
  def about; end
  def services; end
  def portfolio; end
  def contact; end

  def image_mapping
    {
      "app/assets/images/LasryLetter.png" => "http://res.cloudinary.com/dqe5h0j32/image/upload/f_auto,q_auto/v1692741477/rgaunlvg01lmyn6e3wzd.png",
      "app/assets/images/Website-Thumbnail.png" => "http://res.cloudinary.com/dqe5h0j32/image/upload/f_auto,q_auto/v1692741478/pcxjfmz45psso1nqabl8.png",
      "app/assets/images/acdpbill.png" => "http://res.cloudinary.com/dqe5h0j32/image/upload/f_auto,q_auto/v1692741479/mrxvhq4hyo767uno81aq.png",
      "app/assets/images/acdplogo.png" => "http://res.cloudinary.com/dqe5h0j32/image/upload/f_auto,q_auto/v1692741480/htjxhf8ic8nriwhtvnkw.png",
      "app/assets/images/alamanceforwardlogo.png" => "http://res.cloudinary.com/dqe5h0j32/image/upload/f_auto,q_auto/v1692741481/x14tgjcpokfrksduif2n.png",
      "app/assets/images/alamancepride.png" => "http://res.cloudinary.com/dqe5h0j32/image/upload/f_auto,q_auto/v1692741482/lwwhwggxp7wt70c3jp8x.png",
      "app/assets/images/background_image.svg" => "http://res.cloudinary.com/dqe5h0j32/image/upload/f_auto,q_auto/v1692741485/zkxa5fofb4xft83kdf18.svg",
      "app/assets/images/background_image_2.svg" => "http://res.cloudinary.com/dqe5h0j32/image/upload/f_auto,q_auto/v1692741489/mxujex3e5f4vb4pjjbnu.svg",
      "app/assets/images/capitolhillbg.jpg" => "http://res.cloudinary.com/dqe5h0j32/image/upload/f_auto,q_auto/v1692741492/pwtpoq7yj7xospivxpeq.jpg",
      "app/assets/images/consulting.png" => "http://res.cloudinary.com/dqe5h0j32/image/upload/f_auto,q_auto/v1692741493/yigcmimf6klpn1yo3zid.avif",
      "app/assets/images/cridtcard.png" => "http://res.cloudinary.com/dqe5h0j32/image/upload/f_auto,q_auto/v1692741494/djdebfqtk5sfr4tgnddz.png",
      "app/assets/images/equalact.jpeg" => "http://res.cloudinary.com/dqe5h0j32/image/upload/f_auto,q_auto/v1692741495/uetbpfum65xmbgsdnsqh.jpg",
      "app/assets/images/fammadone.jpg" => "http://res.cloudinary.com/dqe5h0j32/image/upload/f_auto,q_auto/v1692741496/dknjkair5fjgskbzqwdh.jpg",
      "app/assets/images/fammguide.png" => "http://res.cloudinary.com/dqe5h0j32/image/upload/f_auto,q_auto/v1692741498/xrf6v9girjgkrpyovhm4.png",
      "app/assets/images/fammlogo.png" => "http://res.cloudinary.com/dqe5h0j32/image/upload/f_auto,q_auto/v1692741499/as7mtdpm6cqvrflgh788.png",
      "app/assets/images/fammservices.png" => "http://res.cloudinary.com/dqe5h0j32/image/upload/f_auto,q_auto/v1692741500/bclxjmigtbgazxl0cron.jpg",
      "app/assets/images/fammworkone.png" => "http://res.cloudinary.com/dqe5h0j32/image/upload/f_auto,q_auto/v1692741501/wulkyovxeff8vef6ycu2.webp",
      "app/assets/images/fammworktwo.png" => "http://res.cloudinary.com/dqe5h0j32/image/upload/f_auto,q_auto/v1692741502/i18bujot2buwxshw0ck4.png",
      "app/assets/images/final_logo_web.svg" => "http://res.cloudinary.com/dqe5h0j32/image/upload/f_auto,q_auto/v1692741503/kyouwfilstnuthnovgex.svg",
      "app/assets/images/isaacweb.jpg" => "http://res.cloudinary.com/dqe5h0j32/image/upload/f_auto,q_auto/v1692741504/d11rgexnnyzozrctxyxz.jpg",
      "app/assets/images/kp2.png" => "http://res.cloudinary.com/dqe5h0j32/image/upload/f_auto,q_auto/v1692741506/gixv5093xtr2bvu05prv.png",
      "app/assets/images/kristenpowersportrait.jpg" => "http://res.cloudinary.com/dqe5h0j32/image/upload/f_auto,q_auto/v1692741507/hsfpqok7inxocenfydzh.jpg",
      "app/assets/images/latinxedlogo.png" => "http://res.cloudinary.com/dqe5h0j32/image/upload/f_auto,q_auto/v1692741508/kbajxyrqgn5hbszo6ypt.png",
      "app/assets/images/latinxedreport.png" => "http://res.cloudinary.com/dqe5h0j32/image/upload/f_auto,q_auto/v1692741513/gbhae6odxtaaynhehcts.png",
      "app/assets/images/monarchwebsite.png" => "http://res.cloudinary.com/dqe5h0j32/image/upload/f_auto,q_auto/v1692741514/dkzkmvlrznz0unwilqnq.png",
      "app/assets/images/ncdplogo.png" => "http://res.cloudinary.com/dqe5h0j32/image/upload/f_auto,q_auto/v1692741515/sqczidbhydbhsytinlnk.png",
      "app/assets/images/newpoderlatinxlogo.png" => "http://res.cloudinary.com/dqe5h0j32/image/upload/f_auto,q_auto/v1692741516/po8lrm1aeiqv5cmvkwgi.png",
      "app/assets/images/palacionacional.png" => "http://res.cloudinary.com/dqe5h0j32/image/upload/f_auto,q_auto/v1692741516/pynyzgrky07kqk81dyxz.avif",
      "app/assets/images/pardonpeople.png" => "http://res.cloudinary.com/dqe5h0j32/image/upload/f_auto,q_auto/v1692741518/z04gjqs9ayew7lsi1rqh.png",
      "app/assets/images/passequalact.png" => "http://res.cloudinary.com/dqe5h0j32/image/upload/f_auto,q_auto/v1692741520/ekdihyrxmngcioy1dwxm.png",
      "app/assets/images/poderbbb.png" => "http://res.cloudinary.com/dqe5h0j32/image/upload/f_auto,q_auto/v1692741534/lyxbhxlrihnzzfq16fqb.png",
      "app/assets/images/podergraphic.png" => "http://res.cloudinary.com/dqe5h0j32/image/upload/f_auto,q_auto/v1692741535/mu6fhjhcnbyg1yhg1i64.png",
      "app/assets/images/poderlatinxfour.jpeg" => "http://res.cloudinary.com/dqe5h0j32/image/upload/f_auto,q_auto/v1692741537/xahvxkxgvq6pvzyurojw.jpg",
      "app/assets/images/portfoliobg.png" => "http://res.cloudinary.com/dqe5h0j32/image/upload/f_auto,q_auto/v1692741538/yzyx22vjh2q82nosqt8l.avif",
      "app/assets/images/ricky_house.png" => "http://res.cloudinary.com/dqe5h0j32/image/upload/f_auto,q_auto/v1692741539/z8kvnd8eeskhq5gthbeq.png",
      "app/assets/images/rickybackgroundimage.jpg" => "http://res.cloudinary.com/dqe5h0j32/image/upload/f_auto,q_auto/v1692741540/ahzrvyzpnuipe7whuskw.jpg",
      "app/assets/images/rickycampaignone.png" => "http://res.cloudinary.com/dqe5h0j32/image/upload/f_auto,q_auto/v1692741542/rgveynzadnxk98p0rjms.png",
      "app/assets/images/rickycampaignthree.png" => "http://res.cloudinary.com/dqe5h0j32/image/upload/f_auto,q_auto/v1692741544/gubkycji5opbnyefgkka.png",
      "app/assets/images/rickyimagethree.jpg" => "http://res.cloudinary.com/dqe5h0j32/image/upload/f_auto,q_auto/v1692741545/oit1mq3f66pvddcw0sq7.jpg",
      "app/assets/images/rickyprotest.jpg" => "http://res.cloudinary.com/dqe5h0j32/image/upload/f_auto,q_auto/v1692741546/xzdaatpbxlwvleh7bbqx.jpg",
      "app/assets/images/runtheworldlogo.png" => "http://res.cloudinary.com/dqe5h0j32/image/upload/f_auto,q_auto/v1692741555/mbw5otiplrkczgsxzfgd.png",
      "app/assets/images/servicespage.png" => "http://res.cloudinary.com/dqe5h0j32/image/upload/f_auto,q_auto/v1692741557/jxohsjnllvfjxt6fkngq.avif",
      "app/assets/images/ydaclogo.png" => "http://res.cloudinary.com/dqe5h0j32/image/upload/f_auto,q_auto/v1692741559/eblgkaqo9wvvxo4jwe3j.png"
    }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def cloudinary_image_path(local_path)
      image_mapping[local_path] || local_path
    end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<section id="footer">
  <div class="container-fluid footer-cont">
    <div class="container footer-section">
      <div class="row">
        <div class="col-lg-6 col-md-6">
          <div class="icon-container">
            <div class="icon-box">
              <a href="https://www.linkedin.com/company/monarch-digital-llc/" target="_blank">
                <i class="fa-brands fa-linkedin"></i></a>
            </div>
            <div class="icon-box">
              <a href="" target="_blank">
                <i class="fa-brands fa-square-x-twitter"></i></a>
            </div>
          </div>
          <div class="row pt-3">
            <div class="col-12">
              <p class="footer-text">@ Copyright 2023 Monarch Digital LLC<br>
                All Rights Reserved</p>
            </div>
          </div>
        </div>
        <div class="col-lg-6 col-md-6">
          <h3>
            <div class="display-6" style="font-size: 25px; color: #FFFFFF">
              New Partnerships</div>
            <p class="footer-text pt-3">Isaac Lopez<br>
              isaac.t.lopez@gmail.com</p>
          </h3>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/layouts/_navbar.html.erb
<nav class="navbar bg-dark border-body navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
  <div class="container-fluid">
    <div class="d-flex justify-content-between align-items-center w-100">
      <div class="container logo-box m-0">
        <a class="navbar-brand" href="<%=home_path%>">
          <%= image_tag "final_logo_web.svg", alt: "Monarch Digital", height: "35", class: "d-inline-block align-top" %>
        </a>
      </div>
      <!-- Navbar Toggler -->
      <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
    <!-- Offcanvas Component -->
    <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Menu</h5>
        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
          <li class="nav-item">
            <a class="nav-link contact-hover" href="<%=home_path%>" style="color: #C64DFF;">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link link-hover normal-link" href="<%=about_path%>">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link link-hover normal-link" href="<%=services_path%>">Services</a>
          </li>
          <li class="nav-item">
            <a class="nav-link link-hover normal-link" href="<%=portfolio_path%>">Portfolio</a>
          </li>
        </ul>
        <div>
        </div>
      </div>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Monarch Digital - Branding & Web Development</title>
    <meta name="description" content="Monarch Digital partners with allies to create strategic designs and impactful change. Specializing in branding, web development for non-profits, political campaigns, and advocacy organizations.">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="keywords" content="branding, web development, non-profits, political campaigns, advocacy, design, NGOs">
    <link rel="canonical" href="https://www.monarch-digital.com">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;1,100;1,300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;1,100;1,300&family=Satisfy&display=swap" rel="stylesheet">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
    <meta property="og:title" content="Monarch Digital" />
    <meta property="og:description" content="Empowering Change, Inspiring Action." />
    <meta property="og:image" content="<%= image_url('Website-Thumbnail.png') %>" />
    <meta property="og:url" content="https://www.monarch-digital.com" />
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="Monarch Digital">
    <meta name="twitter:description" content="Empowering Change, Inspiring Action.">
    <meta name="twitter:image" content="<%= image_url('Website-Thumbnail.png') %>">
    <meta name="twitter:url" content="https://www.monarch-digital.com">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.10.2/mdb.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.10.2/mdb.min.js"></script>
    <script>
      $(document).ready(function () {
        $('.carousel').carousel();
      });
    </script>
    <script src="https://code.jquery.com/jquery-3.x.x.min.js"></script>
  </head>
  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
    <%= render "layouts/footer" %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

app/views/pages/about.html.erb
<section id="aboutheader">
  <div class="container-fluid aboutheader-cont">
    <div class="container aboutimage-container">
      <h2 class="about-title">
      </h2>
    </div>
  </div>
</section>
<section id="missionstatement">
  <div class="container-fluid aboutmain-cont justify-content-center">
    <div class="container about-section justify-content-center">
      <div class="row justify-content-center text-center">
        <div class="col-lg-8 col-md-12 col-sm-12">
          <h3 class="display-4 justify-content-center text-center cause-text" style="color: #FFFFFF;">
            <span class="marker-underline">Our Mission
              <div class="underline"></div>
            </span>
          </h3>
          <p class="missionabout-text pt-4">Monarch Digital stands at the intersection of innovation and social change. Collaborating with local and national advocacy groups, political organizations, and movement leaders, we craft digital solutions that resonate with your mission. Our approach is more than just design; it's about empowering your cause with the right tools and strategies to make a real impact.</p>
        </div>
      </div>
    </div>
  </div>
</section>
<section id="Whoweare">
  <div class="container-fluid whoweare-cont">
    <div class="container whowearebg-cont">
      <div class="row">
        <div class="col-lg-7 col-md-12 col-sm-12">
          <div class="row">
            <h2>
              <div class="display-3 text-start">Who we are</div>
            </h2>
          </div>
          <div class="row">
            <div class="col-lg-10 col-md-12 col-sm-12 pb-2">
              <p class="missionabout-text pt-2" style="color: #070D21;">Latino founded and led, we are a small diverse team with professional and proven experience in political campaigns, design, web development, strategy, and advocacy. Our team's unique background extends into various fields, including the criminal and immigration legal system, mental healthcare, and environmental advocacy consultancy. These firsthand experiences not only shape our perspectives but also enable us to engage and collaborate with our partners on a much deeper level.</p>
            </div>
          </div>
        </div>
        <div class="col-lg-5 col-md-12 col-sm-12 whoweare-photos">
          <div class="row justify-content-between photos">
            <div class="col-3 photo-two">
            </div>
            <div class="col-3 photo-three">
            </div>
            <div class="col-3 photo-four">
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<section id="teamdivider">
  <div class="container-fluid team-divider">
  </div>
</section>
<section id="team">
  <div class="container-fluid team-cont">
    <div class="container teamsection-cont">
      <div class="row equal-height justify-content-between">
        <div class="col-lg-6 col-md-12 col-sm-12 teambio-section">
          <h2>
            <div class="display-3 text-start">Isaac Lopez</div>
          </h2>
          <h3>
            <div class="display-6 text-start text-muted" style="font-size: 18px;">Co Founder</div>
          </h3>
          <h4>
            <div class="display-6 text-start text-muted" style="font-size: 22px;">Managing Partner and Digital Director</div>
          </h4>
          <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 pb-2">
              <p class="team-text pt-2" style="color: #070D21;">Isaac Lopez brings a rich blend of professional and personal experience to our boutique agency. As our senior digital director, Isaac specializes in web development and design, underpinned by his experience in high-profile political campaigns and consulting roles with progressive candidates and advocacy organizations. He knows first hand the issues that affect the Latino and immigrant community. This multifaceted experience enables us to connect and collaborate with our partners on a profound level.<br>
                <br>
                Born in Mexico and later emigrating to the United States, Isaac has lived and worked in diverse environments, ranging from international companies to small organizations. His passion for progressive causes began in his teenage years when he volunteered for Barack Obama's 2008 campaign, driven by the need for immigration reform. As a former DACA recipient, better known as a "Dreamer," Isaac has personal insights into the immigration and criminal legal systems. Isaac's work includes shaping branding and digital strategy for a successful high-profile North Carolina legislative campaign, and continuing consulting roles for progressive advocacy organizations.<br>
              </div>
            </div>
          </div>
          <div class="col-lg-6 col-md-12 col-sm-12 teamphotos">
            <div class="row isaacphoto justify-content-center">
              <div class="col-lg-10 col-md-12 col-sm-12 teamphoto-one align-items-center">
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section id="teamdivider">
    <div class="container-fluid team-divider">
    </div>
  </section>
  <section id="team">
    <div class="container-fluid team-cont">
      <div class="container teamsection-cont">
        <div class="row equal-height justify-content-between">
          <div class="col-lg-6 col-md-12 col-sm-12 teambio-section">
            <h2>
              <div class="display-3 text-start">Kristen Powers</div>
            </h2>
            <h3>
              <div class="display-6 text-start text-muted" style="font-size: 18px;">Co Founder</div>
            </h3>
            <h4>
              <div class="display-6 text-start text-muted" style="font-size: 22px;">Managing Partner and Non-Profit Consultant</div>
            </h4>
            <div class="row">
              <div class="col-lg-12 col-md-12 col-sm-12 pb-2">
                <p class="team-text pt-2" style="color: #070D21;">Kristen Powers blends expertise in non-profit management, fundraising, and strategic communications to enrich Monarch Digital's approach. Her strong commitment to values and ability to translate them into action makes her a pivotal force within our team. Kristen's unique vision, dedication, and understanding of community needs intertwine seamlessly with our shared values and progressive focus.<br>
                  <br>
                  A Stanford University alumna, Kristen's dynamic and impressive background includes involvement in rural political campaigns, igniting a fervent passion for fostering positive change in the South. Her tenure as an Executive Director, managing non-profits focused on the criminal legal system and the reintegration of formerly incarcerated individuals, has further sharpened her ability to lead with compassion and innovation. This distinct experience aligns perfectly with Monarch's mission of offering progressive consulting services.<br>
                  <br>
                  Through her advocacy and leadership, Kristen has fundamentally shaped the way Monarch connects with diverse organizations and non-profits, infusing our collaborations with a sense of purpose, creativity, and integrity. Her influence ensures that we stand strong in our values and apply them to everything we do, strengthening our impact on the communities we serve.</p>
              </div>
            </div>
          </div>
          <div class="col-lg-6 col-md-12 col-sm-12 teamphotos">
            <div class="row isaacphoto justify-content-center">
              <div class="col-lg-10 col-md-12 col-sm-12 teamphoto-two align-items-center">
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

app/views/pages/our_work.html.erb
<h1>Our Work</h1>

app/views/pages/services.html.erb
<section id="servicesheader">
  <div class="container-fluid servicesheader-cont">
    <div class="container servicesimage-container"></div>
  </div>
</section>
<section id="servicesstatement">
  <div class="container-fluid servicesmain-cont justify-content-center">
    <div class="container services-section justify-content-center">
      <div class="row justify-content-center text-center">
        <div class="col-lg-9 col-md-12 col-sm-12">
          <h3 class="display-4 justify-content-center text-center cause-text" style="color: #FFFFFF;">
            <span class="marker-underline">Our Services
              <div class="underline"></div>
            </span>
          </h3>
          <p class="missionabout-text pt-4">We have a passion for providing high quality and mission focused solutions that are crafted on the foundation of understanding your needs, obstacles and pain points. This strategy is why partners seek out Monarch Digital as a solid solution for branding, graphic design and digital development, including mail and website.</p>
        </div>
      </div>
    </div>
  </div>
</section>
<section id="services">
  <div class="container-fluid services-cont">
    <div class="container-lg services-section">
      <div class="row justify-content-center">
        <div class="col-12 text-center">
          <h1>
            <div class="justify-content-center display-5" style="color: #FFFFFF;"">
              What we're <span class="good">good</span> at
            </div>
          </h1>
        </div>
      </div>
      <div class="row justify-content-center pt-2 pb-4">
        <div class="col-10 pt-3">
          <div class="card glass-effect" style="">
            <div class="card-body">
              <h5 class="card-title display-6" style="color: #FFFFFF;">Digital Strategy</h5>
              <h6 class="card-subtitle display-6 mb-2" style="color: #CC5FFF; font-size: 20px;">Research Focused</h6>
              <p class="card-text" style="color: #FFFFFF; font-size: 15px;">Our strategic approach is centered on understanding and engaging your target audience with precision. By crafting compelling narratives that resonate, we foster authentic connections that drive your mission forward. Our tailored digital strategies ensure that your message reaches the right people at the right time. </p>
            </div>
          </div>
        </div>
        <div class="col-10 pt-5">
          <div class="card glass-effect" style="">
            <div class="card-body">
              <h5 class="card-title display-6" style="color: #FFFFFF;">Visual Identity</h5>
              <h6 class="card-subtitle display-6 mb-2" style="color: #CC5FFF; font-size: 20px;">Branding & Design</h6>
              <p class="card-text" style="color: #FFFFFF; font-size: 15px;">We believe in the power of visual identity to shape perceptions and convey core values. Through high-quality graphics, expertly crafted brand guides, and logo creation, we transform your vision into a cohesive and visually appealing experience. Whether in digital or print design, our creative expertise delivers.</p>
            </div>
          </div>
        </div>
        <div class="col-10 pt-5">
          <div class="card glass-effect" style="">
            <div class="card-body">
              <h5 class="card-title display-6" style="color: #FFFFFF;">Web Development</h5>
              <h6 class="card-subtitle display-6 mb-2" style="color: #CC5FFF; font-size: 20px;">Aesthetic & Responsive</h6>
              <p class="card-text" style="color: #FFFFFF; font-size: 15px;">We craft custom websites with an emphasis on visually appealing and functional UI/UX and complex design. Our team excels in creating efficient web apps, ensuring a seamless and responsive online presence. With cutting-edge techniques, we make your digital footprint robust and resonant.</p>
            </div>
          </div>
        </div>
        <div class="col-10 pt-5 pb-5">
          <div class="card glass-effect" style="">
            <div class="card-body">
              <h5 class="card-title display-6" style="color: #FFFFFF;">Non-Profit Director Services</h5>
              <h6 class="card-subtitle display-6 mb-2" style="color: #CC5FFF; font-size: 20px;">Fractional Employment</h6>
              <p class="card-text" style="color: #FFFFFF; font-size: 15px;">We offer high-quality support to non-profits during times of transition or growth. Non-profit staff nationwide are overwhelmed and on the verge of burnout. Our fractional director services can provide part-time and/or temporary support to your team. We specialize in remote, small-team executive level support, including operational and development activities.
              </p>
            </div>
          </div>
        </div>
      </div>
      <div class="row justify-content-between pt-2" id="testimonial-row">
        <div class="services col-12-lg text-center">
          <h3 class="testimonial-text" style="color: #FFFFFF; font-size: 25px; font-weight: 300;">
            "Isaac Lopez is an incredibly talented designer and a joy to work with. Our firm highly recommends his agency to organizations looking to elevate their project designs."<br>
            <br>
            Jeronimo Saldana | On Point Studios
          </h3>
        </div>
      </div>
    </div>
  </div>
</section>